### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by muscleman** [us77ipis/veil-node-stratum-proxy#1]
pprpcheader or rxrpcheader undefined

**Comment by us77ipis** [comment]
Then you are running a too old wallet version. Make sure you have the latest wallet version [v1.2.4.1](https://github.com/Veil-Project/veil/releases/tag/v1.2.4.1).

**Comment by us77ipis** [comment]
Or you haven't set a `miningaddress` in the `veil.conf` file. Make sure you followed the guide in the README.

**Comment by muscleman** [comment]
yeah my issue was veil.conf i spelt

miningadress 
not
miningaddress
